workspace 'Instagram.xcworkspace'

target 'Instagram' do
  use_frameworks!
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
end

target 'InstagramData' do
  use_frameworks!
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'RealmSwift'

  target 'InstagramDataTests' do
    inherit! :search_paths
  end

  project '../InstagramData/InstagramData.xcodeproj'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
